In [100]:
import requests
from pathlib import Path
import pandas as pd
from datetime import datetime
from openai import OpenAI
import json
import time
import math
import numpy as np
import re
import os
import tiktoken

In [101]:
try:
    with open(r"klucz_API_AIDEVS.txt", "r") as f:
        api_key = f.read().strip()  # Usuwa ewentualne znaki nowej linii
except FileNotFoundError:
    print("Błąd: Plik klucza API nie został odnaleziony.")
except Exception as e:
    print(f"Wystąpił błąd podczas odczytu pliku: {e}")

try:
    with open(r"klucz_API_openrouter.txt", "r") as f:
        api_key_openrouter = f.read().strip()  # Usuwa ewentualne znaki nowej linii
except FileNotFoundError:
    print("Błąd: Plik klucza API nie został odnaleziony.")
except Exception as e:
    print(f"Wystąpił błąd podczas odczytu pliku: {e}")

In [102]:
url_log = f"https://hub.ag3nts.org/data/{api_key}/failure.log"
url_api = "https://hub.ag3nts.org/verify"

In [103]:
file_path = Path.cwd() / "S02E03"

In [104]:
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key_openrouter, # Wstaw swój klucz
    timeout=30.0
)

In [105]:
response = requests.get(url_log)

if response.status_code == 200:
    # 3. Stwórz folder (jeśli nie istnieje)
    file_path.mkdir(parents=True, exist_ok=True)
    
    # 4. Zapisz plik
    file_log = file_path / "failure.log"
    with open(file_log, 'wb') as f:
        f.write(response.content)
    
    print(f"Plik pobrany i zapisany w: {file_log}")
else:
    print(f"Błąd pobierania! Status kodu: {response.status_code}")

Plik pobrany i zapisany w: C:\Users\mariu\Documents\Python\AI_DEVS_4\S02E03\failure.log

In [106]:
with open(file_log, 'r', encoding='utf-8') as f:
    lines = [x.strip() for x in f.readlines()]

In [107]:
lines[0]

'[2026-04-25 06:00:16] [INFO] Primary feed acknowledgment on WTRPMP received. Rotation profile is smooth.'

In [108]:
def parse_log_line(line):
    """
    Parsuje linię logu i zwraca wyciągnięte dane.
    
    Format oczekiwany: [DD-MM-RRRR HH:MM:SS] [LEVEL] Wiadomość...
    Zwraca słownik lub None, jeśli linia nie pasuje do wzorca.
    """
    pattern = r'\[(\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2})\] \[([A-Z]+)\] (.+)'
    match = re.match(pattern, line.strip())
    
    if not match:
        return None
    
    timestamp_str, level, message = match.groups()
    
    try:
        timestamp = datetime.strptime(timestamp_str, '%Y-%m-%d %H:%M:%S')
    except ValueError:
        timestamp = None
    
    return {
        'line': line,
        'timestamp': timestamp,
        'timestamp_str': timestamp_str,
        'level': level,
        'message': message.strip()
    }

In [109]:
parse_log_line(lines[0])

{'line': '[2026-04-25 06:00:16] [INFO] Primary feed acknowledgment on WTRPMP received. Rotation profile is smooth.',
 'timestamp': datetime.datetime(2026, 4, 25, 6, 0, 16),
 'timestamp_str': '2026-04-25 06:00:16',
 'level': 'INFO',
 'message': 'Primary feed acknowledgment on WTRPMP received. Rotation profile is smooth.'}

In [110]:
parsed_lines = [parse_log_line(x) for x in lines]

In [111]:
df = pd.DataFrame(parsed_lines)

In [112]:
df['event_id'] = df.index

In [113]:
def extract_component_names(message):
    """
    Wyodrębnia nazwy komponentów z wiadomości logu.
    
    Komponenty:
    - Zawsze w wielkich literach (A-Z)
    - Mogą zawierać cyfry (0-9)
    - Bez znaków specjalnych
    
    Zwraca listę wszystkich znalezionych nazw komponentów.
    """
    # Szuka sekwencji składających się z wielkich liter i cyfr, przynajmniej 3 znaki długie
    pattern = r'\b[A-Z][A-Z0-9]{2,}\b'
    
    matches = re.findall(pattern, message)
    
    return list(dict.fromkeys(matches))  # Usuwa duplikaty, zachowując kolejność

In [114]:
df['component_names'] = [extract_component_names(x) for x in df['message']]

In [115]:
df

,line,timestamp,timestamp_str,level,message,event_id,component_names
0,[2026-04-25 06:00:16] [INFO] Primary feed ackn...,2026-04-25 06:00:16,2026-04-25 06:00:16,INFO,Primary feed acknowledgment on WTRPMP received...,0,[WTRPMP]
1,[2026-04-25 06:00:42] [INFO] Waste routing tel...,2026-04-25 06:00:42,2026-04-25 06:00:42,INFO,Waste routing telemetry from WSTPOOL2 is synch...,1,[WSTPOOL2]
2,[2026-04-25 06:01:09] [INFO] Coolant circulati...,2026-04-25 06:01:09,2026-04-25 06:01:09,INFO,Coolant circulation pulse from WTRPMP is activ...,2,"[WTRPMP, ECCS8]"
3,[2026-04-25 06:01:35] [INFO] Steam pressure re...,2026-04-25 06:01:35,2026-04-25 06:01:35,INFO,Steam pressure readback from STMTURB12 is with...,3,[STMTURB12]
4,[2026-04-25 06:02:01] [INFO] Thermal scan on E...,2026-04-25 06:02:01,2026-04-25 06:02:01,INFO,Thermal scan on ECCS8 completed. Pump manifold...,4,[ECCS8]
...,...,...,...,...,...,...,...
2132,[2026-04-25 21:35:15] [WARN] Fill trajectory i...,2026-04-25 21:35:15,2026-04-25 21:35:15,WARN,Fill trajectory in WTANK07 is slower than expe...,2132,[WTANK07]
2133,[2026-04-25 21:35:41] [WARN] Cooling reserve t...,2026-04-25 21:35:41,2026-04-25 21:35:41,WARN,Cooling reserve trend in WTANK07 keeps falling...,2133,"[WTANK07, ECCS8]"
2134,[2026-04-25 21:36:07] [ERRO] Coolant level in ...,2026-04-25 21:36:07,2026-04-25 21:36:07,ERRO,Coolant level in WTANK07 is below critical res...,2134,[WTANK07]
2135,[2026-04-25 21:36:34] [WARN] Cooling reserve t...,2026-04-25 21:36:34,2026-04-25 21:36:34,WARN,Cooling reserve trend in WTANK07 keeps falling...,2135,"[WTANK07, ECCS8]"
2136,[2026-04-25 21:37:00] [CRIT] Final trip comple...,2026-04-25 21:37:00,2026-04-25 21:37:00,CRIT,Final trip complete because WTANK07 remained u...,2136,"[WTANK07, FIRMWARE]"

In [116]:
df.groupby('level').size()

level
CRIT     114
ERRO     282
INFO    1247
WARN     494
dtype: int64

In [117]:
w = df.groupby(['message','level']).size()
for _,x in w.reset_index().iterrows():
    print(x)

message    Actuator response packet from STMTURB12 accept...
level                                                   INFO
0                                                         99
Name: 0, dtype: object
message    Advisory threshold crossed on WTANK07. Control...
level                                                   WARN
0                                                          2
Name: 1, dtype: object
message    Baseline diagnostics for ECCS8 completed succe...
level                                                   INFO
0                                                          2
Name: 2, dtype: object
message    Baseline diagnostics for FIRMWARE completed su...
level                                                   INFO
0                                                          4
Name: 3, dtype: object
message    Baseline diagnostics for PWR01 completed succe...
level                                                   INFO
0                                                          2
Name: 4, dtype: object
message    Baseline diagnostics for STMTURB12 completed s...
level                                                   INFO
0                                                          3
Name: 5, dtype: object
message    Baseline diagnostics for WSTPOOL2 completed su...
level                                                   INFO
0                                                          1
Name: 6, dtype: object
message    Baseline diagnostics for WTANK07 completed suc...
level                                                   INFO
0                                                          3
Name: 7, dtype: object
message    Baseline diagnostics for WTRPMP completed succ...
level                                                   INFO
0                                                          5
Name: 8, dtype: object
message    Boot sequence checkpoint accepted on FIRMWARE....
level                                                   INFO
0                                                        130
Name: 9, dtype: object
message    Control response from WTANK07 exceeded error b...
level                                                   ERRO
0                                                          2
Name: 10, dtype: object
message    Coolant circulation pulse from WTRPMP is activ...
level                                                   INFO
0                                                        136
Name: 11, dtype: object
message    Coolant inventory in WTANK07 is below critical...
level                                                   CRIT
0                                                          1
Name: 12, dtype: object
message    Coolant level in WTANK07 is below critical res...
level                                                   ERRO
0                                                         41
Name: 13, dtype: object
message    Cooling efficiency on ECCS8 dropped below oper...
level                                                   ERRO
0                                                         21
Name: 14, dtype: object
message    Cooling reserve trend in WTANK07 keeps falling...
level                                                   WARN
0                                                         39
Name: 15, dtype: object
message    Critical boundary exceeded on ECCS8. Emergency...
level                                                   CRIT
0                                                          1
Name: 16, dtype: object
message    Cross-check between FIRMWARE and hardware inte...
level                                                   ERRO
0                                                          1
Name: 17, dtype: object
message    ECCS8 cannot remove heat with the current WTAN...
level                                                   CRIT
0                                                         22
Name: 18, dtype: object
message    ECCS8 core cooling cannot maintain safe gradie...
level                                                   CRIT
0                                                          9
Name: 19, dtype: object
message    ECCS8 failed a recovery step in the active seq...
level                                                   ERRO
0                                                          1
Name: 20, dtype: object
message    ECCS8 fails to recover thermal margin while WT...
level                                                   ERRO
0                                                         26
Name: 21, dtype: object
message    ECCS8 reported runaway outlet temperature. Pro...
level                                                   CRIT
0                                                          9
Name: 22, dtype: object
message    ECCS8 reports rising return temperature. Cooli...
level                                                   WARN
0                                                         51
Name: 23, dtype: object
message    ECCS8 return circuit temperature rose faster t...
level                                                   ERRO
0                                                         19
Name: 24, dtype: object
message    ECCS8 returned inconsistent feedback under loa...
level                                                   ERRO
0                                                          1
Name: 25, dtype: object
message    ECCS8 shows moderate parameter drift during in...
level                                                   WARN
0                                                          1
Name: 26, dtype: object
message    ECCS8 telemetry sample accepted by control bus...
level                                                   INFO
0                                                          3
Name: 27, dtype: object
message    FIRMWARE entered emergency guard branch after ...
level                                                   CRIT
0                                                         16
Name: 28, dtype: object
message    FIRMWARE reported nominal response during rout...
level                                                   INFO
0                                                          6
Name: 29, dtype: object
message    FIRMWARE reports a trend outside preferred sta...
level                                                   WARN
0                                                          1
Name: 30, dtype: object
message    FIRMWARE telemetry sample accepted by control ...
level                                                   INFO
0                                                          5
Name: 31, dtype: object
message    FIRMWARE validation queue returned nonblocking...
level                                                   ERRO
0                                                         18
Name: 32, dtype: object
message    FIRMWARE watchdog acknowledged delayed subsyst...
level                                                   WARN
0                                                         47
Name: 33, dtype: object
message    Fill trajectory in WTANK07 is slower than expe...
level                                                   WARN
0                                                         37
Name: 34, dtype: object
message    Final trip complete because WTANK07 remained u...
level                                                   CRIT
0                                                          1
Name: 35, dtype: object
message    Flow margin on WTRPMP is below preferred start...
level                                                   WARN
0                                                         41
Name: 36, dtype: object
message    Heat transfer path to WSTPOOL2 is saturated. D...
level                                                   ERRO
0                                                         19
Name: 37, dtype: object
message    Input ripple on PWR01 crossed warning limits. ...
level                                                   WARN
0                                                         40
Name: 38, dtype: object
message    Insufficient cooling capacity confirmed after ...
level                                                   CRIT
0                                                          1
Name: 39, dtype: object
message    Level sensor reconciliation for WTANK07 return...
level                                                   WARN
0                                                         49
Name: 40, dtype: object
message    Operational fault persisted on ECCS8 after ret...
level                                                   ERRO
0                                                          1
Name: 41, dtype: object
message    Operational fault persisted on WTANK07 after r...
level                                                   ERRO
0                                                          2
Name: 42, dtype: object
message    PWR01 can no longer sustain stable feed for co...
level                                                   CRIT
0                                                         14
Name: 43, dtype: object
message    PWR01 failed a recovery step in the active seq...
level                                                   ERRO
0                                                          1
Name: 44, dtype: object
message    PWR01 reported nominal response during routine...
level                                                   INFO
0                                                          2
Name: 45, dtype: object
message    PWR01 telemetry sample accepted by control bus...
level                                                   INFO
0                                                          2
Name: 46, dtype: object
message    PWR01 transient disturbed auxiliary pump contr...
level                                                   ERRO
0                                                         26
Name: 47, dtype: object
message    Power bus handshake confirmed on PWR01. Input ...
level                                                   INFO
0                                                        109
Name: 48, dtype: object
message    Power stability on PWR01 is highly unstable un...
level                                                   WARN
0                                                          1
Name: 49, dtype: object
message    Pressure jitter near STMTURB12 is above baseli...
level                                                   WARN
0                                                         49
Name: 50, dtype: object
message    Preventive warning issued for WTANK07 due to u...
level                                                   WARN
0                                                          1
Name: 51, dtype: object
message    Preventive warning issued for WTRPMP due to un...
level                                                   WARN
0                                                          1
Name: 52, dtype: object
message    Primary feed acknowledgment on WTRPMP received...
level                                                   INFO
0                                                        132
Name: 53, dtype: object
message    Reservoir telemetry from WTANK07 updated. Fill...
level                                                   INFO
0                                                        118
Name: 54, dtype: object
message    STMTURB12 decoupling sequence forced by therma...
level                                                   CRIT
0                                                          7
Name: 55, dtype: object
message    STMTURB12 feedback loop exceeded correction bu...
level                                                   ERRO
0                                                         17
Name: 56, dtype: object
message    STMTURB12 reported nominal response during rou...
level                                                   INFO
0                                                          3
Name: 57, dtype: object
message    STMTURB12 telemetry sample accepted by control...
level                                                   INFO
0                                                          1
Name: 58, dtype: object
message    Safety bootstrap read missing environment mark...
level                                                   CRIT
0                                                          1
Name: 59, dtype: object
message    Service heartbeat for ECCS8 arrived on schedul...
level                                                   INFO
0                                                          2
Name: 60, dtype: object
message    Service heartbeat for FIRMWARE arrived on sche...
level                                                   INFO
0                                                          5
Name: 61, dtype: object
message    Service heartbeat for STMTURB12 arrived on sch...
level                                                   INFO
0                                                          6
Name: 62, dtype: object
message    Service heartbeat for WSTPOOL2 arrived on sche...
level                                                   INFO
0                                                          1
Name: 63, dtype: object
message    Service heartbeat for WTANK07 arrived on sched...
level                                                   INFO
0                                                          3
Name: 64, dtype: object
message    Service heartbeat for WTRPMP arrived on schedu...
level                                                   INFO
0                                                          3
Name: 65, dtype: object
message    Steam pressure readback from STMTURB12 is with...
level                                                   INFO
0                                                        104
Name: 66, dtype: object
message    Synchronization token validated by FIRMWARE. R...
level                                                   INFO
0                                                        128
Name: 67, dtype: object
message    Thermal drift on ECCS8 exceeds advisory thresh...
level                                                   WARN
0                                                         55
Name: 68, dtype: object
message    Thermal scan on ECCS8 completed. Pump manifold...
level                                                   INFO
0                                                         99
Name: 69, dtype: object
message    WSTPOOL2 absorption path reached emergency bou...
level                                                   CRIT
0                                                          9
Name: 70, dtype: object
message    WSTPOOL2 entered critical protection state dur...
level                                                   CRIT
0                                                          1
Name: 71, dtype: object
message    WSTPOOL2 reported nominal response during rout...
level                                                   INFO
0                                                          4
Name: 72, dtype: object
message    WSTPOOL2 shows moderate parameter drift during...
level                                                   WARN
0                                                          1
Name: 73, dtype: object
message    WTANK07 coolant level is below critical thresh...
level                                                   CRIT
0                                                          7
Name: 74, dtype: object
message    WTANK07 failed a recovery step in the active s...
level                                                   ERRO
0                                                          1
Name: 75, dtype: object
message    WTANK07 indicates unstable refill trend. Avail...
level                                                   ERRO
0                                                         21
Name: 76, dtype: object
message    WTANK07 level estimate dropped near minimum re...
level                                                   ERRO
0                                                         23
Name: 77, dtype: object
message    WTANK07 reported nominal response during routi...
level                                                   INFO
0                                                          1
Name: 78, dtype: object
message    WTANK07 reports a trend outside preferred star...
level                                                   WARN
0                                                          1
Name: 79, dtype: object
message    WTANK07 returned inconsistent feedback under l...
level                                                   ERRO
0                                                          2
Name: 80, dtype: object
message    WTANK07 telemetry sample accepted by control b...
level                                                   INFO
0                                                          1
Name: 81, dtype: object
message    WTRPMP duty cycle is elevated for current load...
level                                                   WARN
0                                                         31
Name: 82, dtype: object
message    WTRPMP lost stable prime under peak thermal de...
level                                                   CRIT
0                                                         15
Name: 83, dtype: object
message    WTRPMP reported nominal response during routin...
level                                                   INFO
0                                                          4
Name: 84, dtype: object
message    WTRPMP reported repeated cavitation signatures...
level                                                   ERRO
0                                                         19
Name: 85, dtype: object
message    WTRPMP suction profile is inconsistent with ex...
level                                                   ERRO
0                                                         20
Name: 86, dtype: object
message    WTRPMP telemetry sample accepted by control bu...
level                                                   INFO
0                                                          8
Name: 87, dtype: object
message    Waste heat relay to WSTPOOL2 is approaching so...
level                                                   WARN
0                                                         46
Name: 88, dtype: object
message    Waste routing telemetry from WSTPOOL2 is synch...
level                                                   INFO
0                                                        112
Name: 89, dtype: object

In [118]:
def estimate_tokens(text, model="cl100k_base"):
    """Szacuje liczbę tokenów używając tiktoken."""
    encoding = tiktoken.get_encoding(model)
    return len(encoding.encode(text))

In [136]:
def filter_messages(level = [], component = [], regex = ""):
    # 1️⃣ Praca na kopii, aby nie modyfikować oryginału
    df_out = df.copy()
    
    # Inicjalizacja mask boolean (domyślnie True dla wszystkich wierszy)
    mask_level = pd.Series(True, index=df.index)
    mask_comp  = pd.Series(True, index=df.index)
    mask_reg   = pd.Series(True, index=df.index)
    
    # 2️⃣ Filtrowanie po poziomie ważności (level)
    if len(level)>0:
        mask_level = df_out['level'].isin(level)
        
    # 3️⃣ Filtrowanie po nazwach komponentów (component_names jako lista wewnątrz komórki)
    if len(component)>0:
        comp_set = set(component)
        def check_overlap(val):
            return bool(set(val) & comp_set)
            
        mask_comp = df_out['component_names'].apply(check_overlap)
        
    # 4️⃣ Filtrowanie po regex w kolumnie 'line'
    if regex!="":
        try:
            #safe_regex = re.sub(r'\((?!\?:)', '(?:', regex)
            mask_reg = df_out['line'].str.contains(regex, na=False, regex=True)
            #mask_reg = df_out['line'].str.contains(safe_regex, na=False, regex=True)
        except re.error as e:
            raise ValueError(f"Nieprawidłowy wzorzec regex: '{regex}'. Błąd: {e}") from e
            
    # 5️⃣ Połączenie wszystkich warunków (koniunkcja AND) i zwrócenie wyniku
    combined_mask = mask_level & mask_comp & mask_reg
    return df_out[combined_mask]

In [137]:
filter_messages(level=['WARN'],regex=r"(interlock|threshold)")

C:\Users\mariu\AppData\Local\Temp\ipykernel_21928\4090008025.py:26: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask_reg = df_out['line'].str.contains(regex, na=False, regex=True)

,line,timestamp,timestamp_str,level,message,event_id,component_names
7,[2026-04-25 06:03:20] [WARN] Thermal drift on ...,2026-04-25 06:03:20,2026-04-25 06:03:20,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,7,[ECCS8]
24,[2026-04-25 06:10:48] [WARN] Thermal drift on ...,2026-04-25 06:10:48,2026-04-25 06:10:48,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,24,[ECCS8]
93,[2026-04-25 06:41:03] [WARN] Thermal drift on ...,2026-04-25 06:41:03,2026-04-25 06:41:03,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,93,[ECCS8]
200,[2026-04-25 07:27:59] [WARN] Thermal drift on ...,2026-04-25 07:27:59,2026-04-25 07:27:59,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,200,[ECCS8]
345,[2026-04-25 08:31:34] [WARN] Thermal drift on ...,2026-04-25 08:31:34,2026-04-25 08:31:34,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,345,[ECCS8]
356,[2026-04-25 08:36:23] [WARN] Thermal drift on ...,2026-04-25 08:36:23,2026-04-25 08:36:23,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,356,[ECCS8]
408,[2026-04-25 08:59:12] [WARN] Thermal drift on ...,2026-04-25 08:59:12,2026-04-25 08:59:12,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,408,[ECCS8]
467,[2026-04-25 09:25:04] [WARN] Thermal drift on ...,2026-04-25 09:25:04,2026-04-25 09:25:04,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,467,[ECCS8]
504,[2026-04-25 09:41:18] [WARN] Thermal drift on ...,2026-04-25 09:41:18,2026-04-25 09:41:18,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,504,[ECCS8]
531,[2026-04-25 09:53:08] [WARN] Thermal drift on ...,2026-04-25 09:53:08,2026-04-25 09:53:08,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,531,[ECCS8]
604,[2026-04-25 10:25:09] [WARN] Thermal drift on ...,2026-04-25 10:25:09,2026-04-25 10:25:09,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,604,[ECCS8]
610,[2026-04-25 10:27:47] [WARN] Thermal drift on ...,2026-04-25 10:27:47,2026-04-25 10:27:47,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,610,[ECCS8]
620,[2026-04-25 10:32:10] [WARN] Thermal drift on ...,2026-04-25 10:32:10,2026-04-25 10:32:10,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,620,[ECCS8]
767,[2026-04-25 11:36:38] [WARN] Thermal drift on ...,2026-04-25 11:36:38,2026-04-25 11:36:38,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,767,[ECCS8]
811,[2026-04-25 11:55:56] [WARN] Thermal drift on ...,2026-04-25 11:55:56,2026-04-25 11:55:56,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,811,[ECCS8]
823,[2026-04-25 12:01:11] [WARN] Thermal drift on ...,2026-04-25 12:01:11,2026-04-25 12:01:11,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,823,[ECCS8]
914,[2026-04-25 12:41:06] [WARN] Thermal drift on ...,2026-04-25 12:41:06,2026-04-25 12:41:06,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,914,[ECCS8]
934,[2026-04-25 12:49:52] [WARN] Advisory threshol...,2026-04-25 12:49:52,2026-04-25 12:49:52,WARN,Advisory threshold crossed on WTANK07. Control...,934,[WTANK07]
962,[2026-04-25 13:02:09] [WARN] Thermal drift on ...,2026-04-25 13:02:09,2026-04-25 13:02:09,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,962,[ECCS8]
1012,[2026-04-25 13:24:04] [WARN] Thermal drift on ...,2026-04-25 13:24:04,2026-04-25 13:24:04,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1012,[ECCS8]
1063,[2026-04-25 13:46:26] [WARN] Thermal drift on ...,2026-04-25 13:46:26,2026-04-25 13:46:26,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1063,[ECCS8]
1140,[2026-04-25 14:20:13] [WARN] Thermal drift on ...,2026-04-25 14:20:13,2026-04-25 14:20:13,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1140,[ECCS8]
1153,[2026-04-25 14:25:55] [WARN] Thermal drift on ...,2026-04-25 14:25:55,2026-04-25 14:25:55,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1153,[ECCS8]
1164,[2026-04-25 14:30:44] [WARN] Thermal drift on ...,2026-04-25 14:30:44,2026-04-25 14:30:44,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1164,[ECCS8]
1183,[2026-04-25 14:39:04] [WARN] Thermal drift on ...,2026-04-25 14:39:04,2026-04-25 14:39:04,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1183,[ECCS8]
1185,[2026-04-25 14:39:57] [WARN] Thermal drift on ...,2026-04-25 14:39:57,2026-04-25 14:39:57,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1185,[ECCS8]
1230,[2026-04-25 14:59:41] [WARN] Thermal drift on ...,2026-04-25 14:59:41,2026-04-25 14:59:41,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1230,[ECCS8]
1282,[2026-04-25 15:22:29] [WARN] Thermal drift on ...,2026-04-25 15:22:29,2026-04-25 15:22:29,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1282,[ECCS8]
1390,[2026-04-25 16:09:51] [WARN] Thermal drift on ...,2026-04-25 16:09:51,2026-04-25 16:09:51,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1390,[ECCS8]
1406,[2026-04-25 16:16:52] [WARN] Thermal drift on ...,2026-04-25 16:16:52,2026-04-25 16:16:52,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1406,[ECCS8]
1414,[2026-04-25 16:20:22] [WARN] Thermal drift on ...,2026-04-25 16:20:22,2026-04-25 16:20:22,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1414,[ECCS8]
1421,[2026-04-25 16:23:26] [WARN] Thermal drift on ...,2026-04-25 16:23:26,2026-04-25 16:23:26,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1421,[ECCS8]
1443,[2026-04-25 16:33:05] [WARN] Thermal drift on ...,2026-04-25 16:33:05,2026-04-25 16:33:05,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1443,[ECCS8]
1458,[2026-04-25 16:39:40] [WARN] Thermal drift on ...,2026-04-25 16:39:40,2026-04-25 16:39:40,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1458,[ECCS8]
1472,[2026-04-25 16:45:48] [WARN] Thermal drift on ...,2026-04-25 16:45:48,2026-04-25 16:45:48,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1472,[ECCS8]
1482,[2026-04-25 16:50:11] [WARN] Thermal drift on ...,2026-04-25 16:50:11,2026-04-25 16:50:11,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1482,[ECCS8]
1508,[2026-04-25 17:01:36] [WARN] Thermal drift on ...,2026-04-25 17:01:36,2026-04-25 17:01:36,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1508,[ECCS8]
1512,[2026-04-25 17:03:21] [WARN] Thermal drift on ...,2026-04-25 17:03:21,2026-04-25 17:03:21,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1512,[ECCS8]
1520,[2026-04-25 17:06:51] [WARN] Thermal drift on ...,2026-04-25 17:06:51,2026-04-25 17:06:51,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1520,[ECCS8]
1556,[2026-04-25 17:22:39] [WARN] Thermal drift on ...,2026-04-25 17:22:39,2026-04-25 17:22:39,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1556,[ECCS8]
1603,[2026-04-25 17:43:15] [WARN] Thermal drift on ...,2026-04-25 17:43:15,2026-04-25 17:43:15,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1603,[ECCS8]
1623,[2026-04-25 17:52:02] [WARN] Thermal drift on ...,2026-04-25 17:52:02,2026-04-25 17:52:02,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1623,[ECCS8]
1651,[2026-04-25 18:04:18] [WARN] Thermal drift on ...,2026-04-25 18:04:18,2026-04-25 18:04:18,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1651,[ECCS8]
1676,[2026-04-25 18:15:16] [WARN] Advisory threshol...,2026-04-25 18:15:16,2026-04-25 18:15:16,WARN,Advisory threshold crossed on WTANK07. Control...,1676,[WTANK07]
1680,[2026-04-25 18:17:01] [WARN] Thermal drift on ...,2026-04-25 18:17:01,2026-04-25 18:17:01,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1680,[ECCS8]
1747,[2026-04-25 18:46:24] [WARN] Thermal drift on ...,2026-04-25 18:46:24,2026-04-25 18:46:24,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1747,[ECCS8]
1776,[2026-04-25 18:59:07] [WARN] Thermal drift on ...,2026-04-25 18:59:07,2026-04-25 18:59:07,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1776,[ECCS8]
1779,[2026-04-25 19:00:26] [WARN] Thermal drift on ...,2026-04-25 19:00:26,2026-04-25 19:00:26,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1779,[ECCS8]
1813,[2026-04-25 19:15:21] [WARN] Thermal drift on ...,2026-04-25 19:15:21,2026-04-25 19:15:21,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1813,[ECCS8]
1832,[2026-04-25 19:23:41] [WARN] Thermal drift on ...,2026-04-25 19:23:41,2026-04-25 19:23:41,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1832,[ECCS8]
1866,[2026-04-25 19:38:36] [WARN] Thermal drift on ...,2026-04-25 19:38:36,2026-04-25 19:38:36,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1866,[ECCS8]
1899,[2026-04-25 19:53:04] [WARN] Thermal drift on ...,2026-04-25 19:53:04,2026-04-25 19:53:04,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1899,[ECCS8]
1940,[2026-04-25 20:11:03] [WARN] Thermal drift on ...,2026-04-25 20:11:03,2026-04-25 20:11:03,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1940,[ECCS8]
1946,[2026-04-25 20:13:41] [WARN] Thermal drift on ...,2026-04-25 20:13:41,2026-04-25 20:13:41,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1946,[ECCS8]
1973,[2026-04-25 20:25:31] [WARN] Thermal drift on ...,2026-04-25 20:25:31,2026-04-25 20:25:31,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,1973,[ECCS8]
2003,[2026-04-25 20:38:40] [WARN] Thermal drift on ...,2026-04-25 20:38:40,2026-04-25 20:38:40,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,2003,[ECCS8]
2068,[2026-04-25 21:07:11] [WARN] Thermal drift on ...,2026-04-25 21:07:11,2026-04-25 21:07:11,WARN,Thermal drift on ECCS8 exceeds advisory thresh...,2068,[ECCS8]

In [148]:
def filtered_messages_as_str(level = [], component = [], regex = ""):
    df1 = filter_messages(level, component, regex)
    return '\n'.join(list(df1['line']))

In [149]:
def submit_log(text):
    headers = {
        "Content-Type": "application/json"
    }
    
    payload = {
        "apikey": api_key,
        "task": "failure",
        "answer": {
            'logs': text
        }
    }
    
    response = requests.post(url_api, data=json.dumps(payload), headers=headers)
    return {'status_code': response.status_code, 'message': response.json()}

In [150]:
SYSTEM_PROMPT = """
You are the Lead Orchestrator for the "failure" task. 
Your sole objective is to condense massive power plant system logs into a verified submission of 
less than 1500 tokens and obtain the success flag {FLG:...}.

AVAILABLE TOOLS: submit_log, delegate
- submit_log: Sends your final condensed log string to technical inspectors.
- delegate: Spawns a fresh Subagent. Pass a clear, structured `message` describing technician feedback, required filters (levels, components, regex), 
    and compression instructions. 
    The tool returns a list of filtered/condensed log strings from the subagent.

WORKFLOW:
1. INITIAL SUBMISSION: Focus on CRIT level messages first, don't focus on regex and components. 
2. FEEDBACK ANALYSIS: Check what is missing from technicians response and include those things in message for delegate tool.
3. DELEGATION: Use delegate with a precise message. Include technician feedback, target levels, components, regex patterns. If you do not know what is any of those elements (feedback/levels/components/regex), then do not include them in the message. The subagent will return filtered log.
4. SUBMIT: Submit filtered log with tool submit_log.
5. ITERATE: Repeat until `{FLG:...}` is received.

STRICT RULES:
- Format per line: `[YYYY-MM-DD HH:MM] [LEVEL] Component/ID description`
- NEVER remove timestamps, severity levels, or component IDs.
- Delegate all filtering/compression tasks. You only orchestrate, parse feedback, and submit. Note that subagent has its own system prompt and knows about token limit.
- The subagent enforces the less than 1500 token limit via paraphrasing if needed. Your job is strategy and API submission.
"""

In [151]:
def system_prompt_subagent(message):
    SYSTEM_PROMPT_SUBAGENT = f"""
[SYSTEM] You are a specialized Log Processing Subagent, spawned dynamically by the Lead Orchestrator for power plant failure log analysis.

OBJECTIVE:
Filter system logs based on explicit criteria in your delegation context, enforce the less than 1500 token limit via strategic paraphrasing if necessary, and return a plain string of properly formatted log strings.

EXECUTION PROTOCOL:
1. Parse the delegation context to extract target `levels`, `components`, `regex`.
2. Use `filter_messages_as_str` tool with the extracted parameters.
3. Run `estimate_tokens` on the combined output string.
4. If tokens exceed 1500: iteratively paraphrase/simplify descriptions while STRICTLY preserving structure: `[YYYY-MM-DD HH:MM] [LEVEL] Message`. Keep one event per line.
5. Return string with filtered/compressed log lines.

CONSTRAINTS:
- NEVER alter timestamps, severity markers, or component identifiers.
- Paraphrasing must maintain technical accuracy and original meaning.

[DELEGATION_CONTEXT]
{message}
    """
    return SYSTEM_PROMPT_SUBAGENT

In [152]:
def delegate(message):
    SYSTEM_PROMPT_SUBAGENT = system_prompt_subagent(message)
    messages = [{"role": "system", "content": SYSTEM_PROMPT_SUBAGENT}]
    max_iterations = 15
    iteration = 0
    
    print("=== Starting FILTERING Sub-Agent ===")
    
    while iteration < max_iterations:
        iteration += 1
        print(f"\n--- Iteration {iteration} ---")
        
        completion = client.chat.completions.create(
            model="openai/gpt-5-mini", 
            messages=messages,
            tools=tools_sub_agent,
            tool_choice="auto"
        )
    
        response_message = completion.choices[0].message
        print('Response message')
        print(response_message)
        #messages.append(response_message)
        messages.append({
            "role": response_message.role,
            "content": response_message.content,
            "tool_calls": response_message.tool_calls
        })
        
        if not response_message.tool_calls:
            print("Model finished without tools. Trying to parse result.")
            break
            
        for tool_call in response_message.tool_calls:
            function_name = tool_call.function.name
            arguments = json.loads(tool_call.function.arguments)
            
            if function_name in tools_sub_agent_map:
                try:
                    result = tools_sub_agent_map[function_name](**arguments)
                    w = {
                        "role": "tool",
                        "name": function_name,
                        "content": json.dumps(result),
                        "tool_call_id": tool_call.id
                    }
                    print(w)
                    messages.append(w)
                except Exception as e:
                    print(f"Error in {function_name}: {e}")
    
    print("=== FILTERING Sub-Agent Finished ===")
    return messages[-1]['content']

In [153]:
tools_main_agent = [
    {
        "type": "function",
        "function": {
            "name": "submit_log",
            "description": "Submits a condensed log string to the verification endpoint. Returns API response containing technical feedback or success flag.",
            "parameters": {
                "type": "object",
                "properties": {
                    "text": {
                        "type": "string",
                        "description": "Multi-line logs with timestamps, severity levels, and log message, each in format: `[YYYY-MM-DD HH:MM] [LEVEL] Message`. One event per line.",
                    },
                },
                    "required": ["text"],
                    "additionalProperties": False
              },
        }
    },

    {
        "type": "function",
        "function": {
            "name": "delegate",
            "description": "Spawns a fresh Subagent to filter and compress logs based on technician feedback. Returns string with filtered and compressed log.",
            "parameters": {
                "type": "object",
                "properties": {
                    "message": {
                        "type": "string",
                        "description": "Detailed instruction for the subagent - include any of: technician feedback, target levels, components to match, regex patterns.",
                    },
                },
                    "required": ["message"],
                    "additionalProperties": False
              },
        }
    },


]

In [154]:
tools_sub_agent = [
    {
        "type": "function",
        "function": {
            "name": "filter_messages_as_str",
            "description": "Filters log entries based on severity levels, component names, or a regex pattern. Returns matching lines as a single newline-separated string.",
            "parameters": {
                "type": "object",
                "properties": {
                    "level": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Target severity levels. If empty, no level filtering.",
                        "minItems": 0,
                    },
                    "component": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Component IDs/names to match. Returns entries with non-empty intersection.. If this list is empty, no filtering on component.",
                        "minItems": 0,
                    },
                    "regex": {
                        "type": "string",
                        "description": "Regex pattern applied to message content for filtering. If it is empty string, filtering based on regex is not applied.",
                    },
                },
                    "required": [],
                    "additionalProperties": False
              },
        }
    },

    {
        "type": "function",
        "function": {
            "name": "estimate_tokens",
            "description": "Estimates the number of tokens in a filtered log string.",
            "parameters": {
                "type": "object",
                "properties": {
                    "text": {
                        "type": "string",
                        "description": "Filtered log text on which number of tokens is estimated.",
                    },
                },
                    "required": ["message"],
                    "additionalProperties": False
              },
        }
    },


]

In [155]:
tools_main_agent_map = {
    'submit_log': submit_log,
    'delegate': delegate,
}

tools_sub_agent_map = {
    'filter_messages_as_str': filtered_messages_as_str,
    'estimate_tokens': estimate_tokens,
}

In [156]:
def main_agent():
    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    max_iterations = 15
    iteration = 0
    
    print("=== Starting Main Agent ===")
    
    while iteration < max_iterations:
        iteration += 1
        print(f"\n--- Iteration {iteration} ---")
        
        completion = client.chat.completions.create(
            model="openai/gpt-5-mini", 
            messages=messages,
            tools=tools_main_agent,
            tool_choice="auto"
        )
    
        response_message = completion.choices[0].message
        print('Response message')
        print(response_message)
        #messages.append(response_message)
        messages.append({
            "role": response_message.role,
            "content": response_message.content,
            "tool_calls": response_message.tool_calls
        })
        
        if not response_message.tool_calls:
            print("Model finished without tools. Trying to parse result.")
            break
            
        for tool_call in response_message.tool_calls:
            function_name = tool_call.function.name
            arguments = json.loads(tool_call.function.arguments)
            
            if function_name in tools_main_agent_map:
                try:
                    result = tools_main_agent_map[function_name](**arguments)
                    w = {
                        "role": "tool",
                        "name": function_name,
                        "content": json.dumps(result),
                        "tool_call_id": tool_call.id
                    }
                    print(w)
                    messages.append(w)
                except Exception as e:
                    print(f"Error in {function_name}: {e}")
    
    print("=== Main Agent Finished ===")

In [157]:
main_agent()

=== Starting Main Agent ===

--- Iteration 1 ---
Response message
ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_4vf1zQnkXQOhiDi4NDK6aM4k', function=Function(arguments='{"message":"INITIAL FILTER: Technician feedback not yet available. Task: extract and compress CRIT level log events only across all components. Requirements: \\n- Target levels: CRIT only.\\n- Do not filter by component or regex.\\n- Preserve exact timestamp, severity level, and component/ID in each line.\\n- Format per line: \'[YYYY-MM-DD HH:MM] [LEVEL] Component/ID description\'.\\n- Remove duplicate or near-duplicate messages but keep first occurrence and note counts if repeats (e.g., \'(x4)\').\\n- Maintain chronological order.\\n- Compress verbose descriptions by paraphrasing while keeping the essential facts (fault, location, metric values, action taken).\\n- Ensure final condensed output is a single string, under 1500 tokens (you enforce this via paraphrasing), suitable for submission.\\nReturn: a condensed log string containing only CRIT events."}', name='delegate'), type='function', index=0)], reasoning=None, reasoning_details=[{'type': 'reasoning.encrypted', 'data': 'gAAAAABp7fizJVLoyj3bHkamfodJ4F8CzQjoHfBApXw9xCyjmXnG41CywEV67NwcehDxqrS1iiRy7JKX0FgFlmM9WJn2MCV0pA_DjIcauwmb__Pq0BrrGku47_psI_nmimfD8NTqWhgnsBsk6wGGAwRB_KdboN4fI14UWolV2xDO5dBjXEmtW-807Tx6S2qqs1zRX66CnPXodSfed4tcfwYo1907UHfilriytoiEJxjOBO8ePheTAqVXjl6IO91KQO-8Y1HTUfIdrWiH67NLO8HPi_K_cNoIltaeJHx7_MV8ps8WJmNWjFNXSPUbL02bJy7iMB2TPJUITIv8qzM-GqlWxFqEdyJjYNKEEG7Jp4ocCrTz1MhGm5YM0MXrFkF_Rjkx0drN5FrYlZhHyHBB1JY3NsAxGNX5FmBzESOu3AJcllh4-mMD01WKBgbRLsAgEN9K9ccTvckTrkzle7jjO-mj63eFp_qzYc8FAujCoxWO1c0j6jPpJbGu1023JCBVEg16AZmC0IUMILenMt1LFlVYnWCsC6qyqZ2koRfidmrh4U0wkEqi5wd7HfxmhbX90723cHf_0RG1PHNFriM_mS-LRk107H5hHzdEzA3uXMjuwYuVE4qA8m6Ro3XbNorq9PyfP4nn29z3wiaOKNRAK8Kv0Arnzz6wltz8GM_c2rpxvljyt7MXCyI2OMEaIwJ9VG8iSlLQpL44c4Pj5xUAsZeA4Ici63mRYMjvtFybxKu2JRTXF2843XJ3U-66zYh9aAstNbSzwSParAHZhwgfqp0mXCXgno5e-0M5tDgYfU89YnArgO9E_NkcwkQZo9HWZKIbXaQ9oB6GEHl07sZ17IaLPrRtaw9ns2N5OG6xgsIVLB5bmCMXD75mOU6FP_bn3yRzxFkYjBKabL2ymsTuBnZW0Z5_dDRxYjBQRyH57VusykaNmEtnqTWEjtF7jfvjiB4FYbq61zu_OXSoLSmRWE17qhELlyfEq1n4dB-xAzGxk31V75sd8_-ELxND9gMtBsmKUzEa7LDiBUIc7E0HgF0e2rxiGzJ9h75bgrEK_PB_2CKbAgU7q_g68OquQyWEax8sQxtMDCfPBdsdtqaUD67Ms1K0eIsRk6BwBrgO_ztLcNQoWI_iGcsNyrhy2hobun-rH1Ck84b6kpATNKIhDhq5hOXE57faaUJERIMr8IXzrJSJ-xzBuAU6YDs_vwLqU2XgBJm65i-miYCQglgaV69Ot1XU5tzpfTRxXoKF7n-r_gbrVdiquRqOYJ3hYzS_bEUJSK_GtTvEuv968Snd8o7X9oRm5-RLwukTr0WOIyBb9Eug2BQaXDEgu1xIOMiaut7cStIvXQW_iBuVjJMmFEmBDLMeBiSB4rwPVzKjHJmlOuNxaHkWT1fAk6MFR_LXc4xC1rEpzeuyGbkiTQ3HC6jaizsg9VsxPIKBevnZEvlbWgZcZppX6EgeW-EbvCbxoo3SyMOFhENEnHxnDxuPAUBVmaT6wxQHKEKa2AduSXutsKVDTp8OwSCC46gDvzy0WQqY7V6VDx5b80HmL5AM9GYWCcGbWcU_pzcPlRXfX2e2SfJSOzPBQ2qc_uyfBpbfk57INQy9lY_AUnbPoHJwgKtScbwo5rGe2Fol85pvRD3dxWRmdwKYrcUpKNqGi6egzDf8jTN7jqstbgv6lmLuXkf3KZ4c64Cfp0_zUpDNJVdSrj0N9kfT2kqwmwNp9SkO-tNFoM1uE1GSryOCeafvp9vsoHrOORiztZGeX1VEiFdGGrbt3CL3v96YB9CpdPfngiqcBTxoIHZ5xB_xiSkOIIlFSkBydpszSTaD3H2FqkNrWZ6RNonVAkkMGMRizQWfVzOgfyRxDKPXMebqBOCCfgHNaXYMDTk-CS-Wu5bd_Cki9wGTAOAHFPdV2dFm-fATOv7n-2K4Ic6dck5TOCb8TTJMC1ZI6NM8Tu1Jyy97RN0oRBPOA6CmWpSLTAEJvRaWl5ToXKojcDudMpuIFOpeRa50xQXy5RZO1IRvjAMlWnc_Pg-6Em3Exo1wmrjq6fsNoE43Ow7Y5-WKbWUUW_BngFNOfcSJE1AUHtS5MJm8ve3g-Q7n_j2tSfLZCx4OTzqvo0jEHbtBVnUUOk7BaNokAjf2E4ChgEhxbes8UEETSH7qOmCs6IXvj9dDBbKtvGW4NN26Za3dvhZ2-cmu_do-wEH9CPC78neJm02bpOfsQPHKx3bAFfmhvJT7ab1CG9UcpxgxnxI0v9Nyfy3ZyZdTWhPXXfpb6xTbiY8KveNJUo0ja2goMvbPEZ8UvedSxQ42f9ZhOnRD3mTe7zYyHE5WCjKb1cxDn3KmDkI4lGJBDa761fNcVoaE30VGoM7Ff_VComLek0H9G1zxO-8dpgVNhzFCeGW1Qc1jqBByouAcOLKmwwa79mvMkPnDC3YSyzIRD1Sl2Xnl8xUD4okoPJ2ySS8bpcoQmLsHu3_A2pF8Q4078-1aXYEIcQPrEQu459BjmmLjKuXa96Rpcyr7RuymILDMH_fnd1phusImgAWyFdmucUwaAGPduVy9uqkSgp-QydM_FpRqIlOu1g0TwAdiVigR6w38AExh6nR_GAvzgAl5y3KCWumdLptKxBnOywNNad2fL4iT0UFVCOqafbBMozAUctp9Ro9KPvVuwMM_MyULn37kp00pAsx8Klkali48AGrPMD9I5KVXZslKH50vBln-mbN_2ssZqsf82qfz1ZvrXgoyZcy2399mMeRkk1A9uY_Ukiu_FhAfbbkj7bGcnAj_VRZGUVZ1lQI-n1Jy1znk2mpt_y5f3bzhg1PoKZsaryA_jdP-H-BBHkVXN4tCJzhtkI8oLmFyLP2gFi62kdHwpLbtBNGLtoi0MuH1jVPNUN-xMNnb80fx8fCRXeokGVWtMjnZfY_gCA==', 'format': 'openai-responses-v1', 'id': 'rs_0aac04db4be668350169edf8b062e881938a4d2057413a7fcb', 'index': 0}])
=== Starting FILTERING Sub-Agent ===

--- Iteration 1 ---
Response message
ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_dAZhW5DfiPaFJ5VmA79gBbvo', function=Function(arguments='{"level":["CRIT"],"component":[],"regex":""}', name='filter_messages_as_str'), type='function', index=0)], reasoning=None, reasoning_details=[{'type': 'reasoning.encrypted', 'data': 'gAAAAABp7fi38RpRdOnCjENZOB3dw_JcIMV_CzwHzuyAw3zhcnC-cXhOs6yiM97djZHZJf4EfUL1p6yLIP2FY9m1Ci9AGkJlONsm5bVH28Eep89qSEmRn9EeELZzu-I_C4GnOezQzpleG3CAlKV9lX1g0deRHhVz_mckqg4Zuw8IhtgLYFgz748-AKO9npT1VY1BAqjm9GblNLXxMXxzjSc_hXAjoPpoQvR6nD4ISTbvosu_30R1jcdFz4H223_-VOKHiRVAWTQ81dZ6RHvd2i0ASoNAyDm7xV-dBsdb5zLpIjA_NzAdIYDCAVubmM9aLkutOFyva2gpaUsUs4b9iQa2Oi958Ooa1r0njqOEHzlILPyDAbyr8Klrw0FfqcR8ZV_Q_0cI8XZPyPwQNsbRq6TpTIFt3QotKRR-yQUtHIF61h9zXIUNGedjjL0sOgNjw1aqDOEeESLNdP4T7HqJK-5NTnJQBVMZ9heDNPPkA3CEs_k_p1fR-A7TvWG3LwlePlVJcC0-Z0r1UPwcZfXF7GDfMJyaakwRdZjwqeul9a67lPP7lLS7Dh7W9hz4tUX6UT8aDHSoVXS_Myry_t7UPFh40f6UqtZ5AgclN4zE2YUmWjYffORrXRPd2QVuo_unDegK8ddK8u0S2iC1lej4L9L5XohVDimQ5XFeEY78QTQ5RAyEREtAHQkmM-HdfX4U9nljfuajyk3HO2mY52-g4d2QHz_ZObAf1rBiKgLrQV4rzH_ionKj2S-OGEIUAfdU4HBrwU0JcevrpnF97AxfrWk0YWXWuddITJ-W_pNv37VFNunjXQ5WJngZDj6F1bYedXJciGJOnSdz_5vhHFq7IIUYGOnVuNlKis87w_swvJvOABGlkwHBbCHdjTWczS6n0zfgqAcsaHQm7tG892Plh2Gd2XSmarR4GKLB5STimihrib7ReRK57pGJUQ06cuNZPvjTNy3dOd149D8hbfQi8YyGqHF5ieGohWQHfLjDE2P5etMUDaMB035Eu5ZNQ28ixY9ra06iFyBxJVwiOFZJ0JtJ8_-YU949pRBk3QZOq2Vmg8fKp00WHyXZuZeuHu4dgiyZrwjqJjDnr-yUDxt2QnszvohMBB8JZ9QkJtADsJVvuHFmd3T_ErKVNFCPLJDqEOcF6OBaIVoONgQYtKyxY67715MHcje9E4ezDDJ-0XnprB3O_xq8KytlKDOCiLZIamYHVsgA-uYVsIkQacbgnSZm3xtdEgDYg_3bZ0ZImv-mAcynatt_rWuZH3dtP7c8fxDIy0HGu7dNUflUvIp-g7RpFYU9GD0Lc2If0ViFxAG_ji2V7-hvOfgTXTUPpAQKzOZTebZKeLxA84nhvIBDjcToNprRnxGUMLIYaINs1Z4nfnVMTi_2YjOfXwQagsQKUKiShX79XgS5gmrM3J8JGav7Bx5CtTeOHmnVv8K5LeIRD_hSNpnbTOpJiqO9nSY6Y03R1FqNFuCbkne2NN8mR-WTSu4oc38xpgA8LxsXRdmpXE7wefaeN9x8JbKLHEPtMfiVA5fLaUEk8J1m5Tku8CL42SCQGxLKxwbwDfgpiQdBMjRiMw6faRQKH0uU2LS9tDb7w60hvcMjIrkhRvGnKZ3nWn-zs_4Ae0cunvBwVE-5bJY4244vD6ht_2BAwh_ihdTjwVW4Bt5wLwabw9w6A1rsx1A-F0U2uUskQFrOtHRjcuEWIEyxDdJM0v6Dd8Mk-ifhRIApx9iWHoOXvmNNofV6DZGPlb62rR4P6U6zSjlKg6OIzBQrmOjz77uV1t_NBv8-Pf6QQ8LzI0HbWvyxOM3UyUy6HWEjfIuYw3Gs1K6W5WuIUbtR8jhNuH_2OutkSCJsH8hLmTRa_IWVprj8aakzsv3j9WHPjxBHlqX5Zc6G1uAtfb5J13LCiwsPTHH9xmJQrlWxUTS00vI163Z_h4blvsfVGVrHUGUJg8qru9uUCKTu5bCX9GCk4R_BvDuOLATBYnHC5qdFSHSMJ0Y4lf5yHo7gK8iDUsvKwO_ncDeM1t6-Ggf_66I1bnz3DP_z4S2C4v3hBEGc', 'format': 'openai-responses-v1', 'id': 'rs_0a014b8b0cb05dad0169edf8b5fa3c81968e67456139f2f73a', 'index': 0}])

In [67]:
from openai.types.chat import ChatCompletionMessage
import inspect
print(inspect.getsource(ChatCompletionMessage))

class ChatCompletionMessage(BaseModel):
    """A chat completion message generated by the model."""

    content: Optional[str] = None
    """The contents of the message."""

    refusal: Optional[str] = None
    """The refusal message generated by the model."""

    role: Literal["assistant"]
    """The role of the author of this message."""

    annotations: Optional[List[Annotation]] = None
    """
    Annotations for the message, when applicable, as when using the
    [web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).
    """

    audio: Optional[ChatCompletionAudio] = None
    """
    If the audio output modality is requested, this object contains data about the
    audio response from the model.
    [Learn more](https://platform.openai.com/docs/guides/audio).
    """

    function_call: Optional[FunctionCall] = None
    """Deprecated and replaced by `tool_calls`.

    The name and arguments of a function that should be called, as generated by the
    model.
    """

    tool_calls: Optional[List[ChatCompletionMessageToolCallUnion]] = None
    """The tool calls generated by the model, such as function calls."""

In [89]:
def delegate_test(message):
    SYSTEM_PROMPT_SUBAGENT = system_prompt_subagent(message)
    messages = [{"role": "system", "content": SYSTEM_PROMPT_SUBAGENT}]
    max_iterations = 15
    iteration = 0
    
    print("=== Starting FILTERING Sub-Agent ===")
    
    while iteration < max_iterations:
        iteration += 1
        print(f"\n--- Iteration {iteration} ---")
        
        completion = client.chat.completions.create(
            model="openai/gpt-5-mini", 
            messages=messages,
            tools=tools_sub_agent,
            tool_choice="auto"
        )
    
        response_message = completion.choices[0].message
        print('Response message')
        print(response_message)
        #messages.append(response_message)
        messages.append({
            "role": response_message.role,
            "content": response_message.content,
            "tool_calls": response_message.tool_calls
        })
        
        if not response_message.tool_calls:
            print("Model finished without tools. Trying to parse result.")
            break
            
        for tool_call in response_message.tool_calls:
            function_name = tool_call.function.name
            arguments = json.loads(tool_call.function.arguments)
            
            if function_name in tools_sub_agent_map:
                try:
                    result = tools_sub_agent_map[function_name](**arguments)
                    w = {
                        "role": "tool",
                        "name": function_name,
                        "content": json.dumps(result),
                        "tool_call_id": tool_call.id
                    }
                    print(w)
                    messages.append(w)
                except Exception as e:
                    print(f"Error in {function_name}: {e}")
    
    print("=== FILTERING Sub-Agent Finished ===")
    return messages[-1]['content']

In [90]:
message_test = "Initial task: extract and compress all CRIT-level log entries from the full system log. Technician feedback: none yet. Target levels: CRIT only. Components: all components/IDs. Regex patterns: none. Constraints and instructions for the subagent:\n- Output must follow exact per-line format: \"[YYYY-MM-DD HH:MM] [LEVEL] Component/ID description\"; do NOT remove or change timestamps, severity levels, or component IDs.\n- Preserve error codes, IDs, and any numeric values. Paraphrase long messages to be concise but keep essential diagnostics (error codes, component IDs, status phrases like \"shutdown\", \"overtemp\", \"failed to start\").\n- Compress repetitive events by keeping representative lines and, where necessary, append \"(xN similar)\" at end of a line while preserving the same format for the representative line and not altering timestamp/level/component/ID positions. If you append counts, ensure they follow the description text separated by a space.\n- Keep total resulting text <1500 tokens. If needed, prioritize messages with explicit failure actions (shutdown, trip, critical fault), unique error codes, or unique component IDs.\n- Do not invent new timestamps or IDs; only include existing lines.\n- Return the filtered/condensed log as a plain string with one event per line.\n\nRespond with the filtered/condensed CRIT-level log."

In [91]:
print(message_test)

Initial task: extract and compress all CRIT-level log entries from the full system log. Technician feedback: none yet. Target levels: CRIT only. Components: all components/IDs. Regex patterns: none. Constraints and instructions for the subagent:
- Output must follow exact per-line format: "[YYYY-MM-DD HH:MM] [LEVEL] Component/ID description"; do NOT remove or change timestamps, severity levels, or component IDs.
- Preserve error codes, IDs, and any numeric values. Paraphrase long messages to be concise but keep essential diagnostics (error codes, component IDs, status phrases like "shutdown", "overtemp", "failed to start").
- Compress repetitive events by keeping representative lines and, where necessary, append "(xN similar)" at end of a line while preserving the same format for the representative line and not altering timestamp/level/component/ID positions. If you append counts, ensure they follow the description text separated by a space.
- Keep total resulting text <1500 tokens. If needed, prioritize messages with explicit failure actions (shutdown, trip, critical fault), unique error codes, or unique component IDs.
- Do not invent new timestamps or IDs; only include existing lines.
- Return the filtered/condensed log as a plain string with one event per line.

Respond with the filtered/condensed CRIT-level log.

In [92]:
w = delegate_test(message_test)

=== Starting FILTERING Sub-Agent ===

--- Iteration 1 ---
Response message
ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_HmWLLTbiLTmON9CIulfbrGyI', function=Function(arguments='{"level":["CRIT"], "component":[], "regex":""}', name='filter_messages_as_str'), type='function', index=0)], reasoning=None, reasoning_details=[{'type': 'reasoning.encrypted', 'data': 'gAAAAABp7fHq1iTkpKpnjtd90y0bSrm905fj7qOhQhX806re-BSkmcrJdFZWeC5HYH6Tj8m8Y5SSdsLysvtQOYwWnC5u0XPN0dXDbpBqP1L177lHGMdtURyhnmJy8e5d2uJZwiw4s-rVHtLTHbQG5pVWVLYQsXOYUfGEHTKPzF0Xa9TpvUlElPVBLizpcVJz_5HVJFus6Cnubpc19V-MgoXci0FJLvXXN7zh83Xde9mJtMMsJBWqqcuH2Z7bC97UP5W_QHIqsA7iiGooIdR5BtupDP_CgOZRLPiQ6h88G0ChpujXxo9D3JC2yQqR3tJsHtSPsTvfr0IbhBUjTYw_BVsK3NSlLjLofOpXmNAZjmS_HmpXKhmG1HZO4ndgNfgzJaxrjq7uRO1Z7FQzzZ1z-9Me5comd0rgxGLFzJa27xBGh2-btz-q8YrrjYzbVzoSU0xSauMB5DhEM47_bw72LgLUH6R7sawAgYrxec3Rp5L1UXeEBe0RLqdvfyzJi1BgUOMIVWPo052IAsKxvzYXKveZ9Tl2Vlq-9QDL77KtytAbMoHnh9Lo8Xhx9rqU-4mzsVetxmMTn_RZmcpxEVMggjtqyLagyQ-KfCir3DcIGXFLNUZWcwrATdIFEV9-nuZ7oNPLtJogO1V54qpaGRgWXQH5-UjcWo6BXy-3fbFXyxlvOKxl_ClUKwXvxkHVIh-VlEk1JWA788dTzK5P4FW3PD7D3pmcFVZhoNsMIyDMNQ9cW7V80gM7czXA8xGA9PXzp3WXJ18GYTHOKCLXk1FFWGgnyLZi6NVtDrdfx1Qtnd34PIEmkZLFcCSDha8c5pyAeiBHaNaZeOqNtg_3UEghe0ovSzKQriS35Puz6YZ8ps_2quhRggRwmCAmoQbIiN126rTurp3eAMtDvJfLEsDVCfYodxsX68G9tgmtc1iD9bdVHE_OR0x2i6fn_9_UIVpJVOjjbRggG5J7bDsze9zfvjUQqGq0HtxVCNAgoDY6pYtEbUqKjxNjJ9Lt78dAN9UR-ah6NRCptY8UYzsLVffa2K78G_Kyxt-ksxWDkN-uzfco_NLUXCRGQwavXxm6sBfMVNjfpVU01Rp9djrqX7I4TDgvLeAdMUmg416c2-_vqq8edDAKfmSaYY2xREFdf4XrbC1ih50jhRIk_ta-w9K1hyLODf_17RpLT6tiqK7xHCbcIQ3y1JRB1-hqxlGUiRDuDWNDbn_qs3mUmYkfrCCDMm6Do3RTC7yeh7QIsP4x5ZLNqyR8XC1-xjOxvDhnPFfIlLLpdtoRIie3MidPnalu7DCUhcpwgVb84MUip30EjOMI0By_LL7iOSoNB_wf0wMnDn4LKwA8ul38cQMt8RfXSgWI6OqR2cxdd8Bm351z0X19hD0oSAvdQ2R5-7XaAFu3sRhTADX_UdaZJQiNQTd1Sd6LonHLnUeNLOZiJvAhlvqvSXzTB0ongWxi_8ow_2EgYVFmUbiDyyDDm4dxZLQHlSmfGv__j442TtowJiR-YAeqPRWgiZu2QfdZSoGM-PJQdKYUF1rqN8kso5xQdM34WDBg4mDB5LiXnWRgtWud5kceix0ho3HzIgIk_rsvw6iTLbiaJVaQQbfbYDGFco7ECoOhtBBifborA72HNriyYij7yt9DkkhTg-kiV9qTzJbzP1Ay95CWvq1bOLaWzxC_MVmFP7m0siS0vjAOJN7D8sy-MjgGnpqghVJV9SeszXGa3ILjYr2ZF6OlvECqeVcvwxeJOT6E-iOMI0lzmvAekHvlj5j9vI_n6ayOUrpRmpA28OKHQ_D0nR39iiYvavFWDrxUlkQ4OuM24UQhyYA1HEiiaEFtLsNPyOtxKVdiPva8Bt-eRswq8ZCJ-IgQ4a2lD3hLXu_28jK4t0OIb0afNmmgzcC-QxV2y2zU7QObtnd05Gk_4_6RErJCxf2FcBr9A5mTnlLbdk39KmxNpZ2_XC5WzVlHkCfHxHVgZCDQ5jbWtp406-y7zv0gwLs495pK-F-yK2bQbT2vzHEkabjOh0SB72r7UoPSa-GGlE9TXbHV5C7-bHgsk5spZ0t1fXEOHAmI_muNompGhMnWw4_kr6VLtdKQWEN_g6mUIi_G30-bWCoEG2JdHF7LSmN5ENViz1hZhc-w3-DU2Bz-eeUElkvT933M_WkizuccmYpl1nCor_en3hfWlfnvVactRhnfggDx3nUHf4oFmcKNS_5HzwiAheepb--shCCgYBUue1OT6yDDHKd0YrDaDb0enCoEzCIqJNmbukK89dvm_kSTsnPrZ0vmri42gs73KKKDucIwGsjaCuDJsyPMjx5u-opCnOvkJnDmIAvNaFeTephW1fU6PL63HC3SBi9toRc6GdZVMP9DS3JVKWKXsDKosa2-0SI2yVGluIkMTpDsV4Rs8DoQG1E8TiqnntXotHb683GIzdDXF5v2Hl3NszxNKJKNbXECVJa6-pnSb_ZvbW34HKu8KnsvM3H1zGZWX4LqU2599FCdmUXABLK0HR8S1oIWcHrl4SonH9oarOLBdtFvbTDI93B9OdnNVR9uPkMHdbtF8WUEAxkxeEaN4XzBTm1ipIn-IvaukdhhBJQTLSUH21Gr_eJTwOFkFvZrQWoE1XavW4HCNUr6mosTUK1Y96if-zqCvi1gNuBALZD9mLhCnd-neQWPOp_tk8kBWB_4exS3_49ux8X5NvcWrAlrAiIuNHSqSRFFuA3_mY96zdxyhm1VZ7v1e9JWaavIE58gERCPnoNoNl21Jq5Osp_IvMaHEBeehtBjNDY2Ol1cr1Pk3Ypmu3CscQtS95FGjLDqUbWFBMJvClFzvPqnoiXAulcekp9TxKu-UIGl0wZ_GOV1R46O587Ca0_pLPPSlTNUlR7wyMcztTG1Cr0Hs2czGHZj1fhXUwSI1u5HJb0D8C0VeJinspxYoA3wNks8NQKdekksbg_FbT4YGZqInRfkgtQmsXx9wDQ-C3ASKbnfR3MmAWzpcIdfKEgAlN5Vvow8aNWW9dwjAB227GVM4pxyZo1PN8a3QKswPA4pezhI5MQhoq1ZoInTEjXkGrtXbe3wiTz9ZKrr2zl1qfmD6To2V_ubDxxulKQKWkwhBhjZl5qevjqTIML8QEfZniVj9Cejtp-uHwho5yppTlvggN2muB9B6lnkoYVMmQ2TB0qOkHJPt93Q0YCN-qqhOXgbWLtz5vJlyiUC6hYA-qEx--lsVe-yx2IDSzxoysd1EnazigiZgjE36CmTdZer7Jg=', 'format': 'openai-responses-v1', 'id': 'rs_0c745983155dfe570169edf1e532088194bbcb6df9a3fc359b', 'index': 0}])
{'role': 'tool', 'name': 'filter_messages_as_str', 'content': '"[2026-04-25 06:04:13] [CRIT] ECCS8 reported runaway outlet temperature. Protection interlock initiated reactor trip.\\n[2026-04-25 06:16:56] [CRIT] WSTPOOL2 absorption path reached emergency boundary. Heat rejection is no longer sufficient.\\n[2026-04-25 08:00:26] [CRIT] ECCS8 core cooling cannot maintain safe gradient. Immediate protective actions are required.\\n[2026-04-25 10:15:56] [CRIT] WTANK07 coolant level is below critical threshold. Shutdown logic is moving to hard trip stage.\\n[2026-04-25 10:35:40] [CRIT] WSTPOOL2 absorption path reached emergency boundary. Heat rejection is no longer sufficient.\\n[2026-04-25 10:45:19] [CRIT] WSTPOOL2 absorption path reached emergency boundary. Heat rejection is no longer sufficient.\\n[2026-04-25 11:01:33] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised.\\n[2026-04-25 11:40:08] [CRIT] ECCS8 core cooling cannot maintain safe gradient. Immediate protective actions are required.\\n[2026-04-25 12:51:11] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 12:56:27] [CRIT] STMTURB12 decoupling sequence forced by thermal risk. Energy conversion is terminated.\\n[2026-04-25 12:57:46] [CRIT] ECCS8 reported runaway outlet temperature. Protection interlock initiated reactor trip.\\n[2026-04-25 13:01:16] [CRIT] ECCS8 reported runaway outlet temperature. Protection interlock initiated reactor trip.\\n[2026-04-25 13:28:01] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised.\\n[2026-04-25 13:37:40] [CRIT] PWR01 can no longer sustain stable feed for cooling auxiliaries. Critical loads are shedding.\\n[2026-04-25 13:40:18] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 14:00:02] [CRIT] STMTURB12 decoupling sequence forced by thermal risk. Energy conversion is terminated.\\n[2026-04-25 14:52:13] [CRIT] STMTURB12 decoupling sequence forced by thermal risk. Energy conversion is terminated.\\n[2026-04-25 14:52:40] [CRIT] Safety bootstrap read missing environment marker SAFETY_CHECK=pass. FIRMWARE continues in restricted validation mode.\\n[2026-04-25 14:57:03] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 15:15:02] [CRIT] ECCS8 reported runaway outlet temperature. Protection interlock initiated reactor trip.\\n[2026-04-25 15:58:53] [CRIT] WSTPOOL2 absorption path reached emergency boundary. Heat rejection is no longer sufficient.\\n[2026-04-25 16:03:16] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised.\\n[2026-04-25 16:05:28] [CRIT] ECCS8 core cooling cannot maintain safe gradient. Immediate protective actions are required.\\n[2026-04-25 16:06:20] [CRIT] WSTPOOL2 absorption path reached emergency boundary. Heat rejection is no longer sufficient.\\n[2026-04-25 16:06:47] [CRIT] WSTPOOL2 entered critical protection state during startup. Immediate shutdown safeguards remain active.\\n[2026-04-25 16:17:44] [CRIT] PWR01 can no longer sustain stable feed for cooling auxiliaries. Critical loads are shedding.\\n[2026-04-25 16:56:46] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 17:07:18] [CRIT] PWR01 can no longer sustain stable feed for cooling auxiliaries. Critical loads are shedding.\\n[2026-04-25 17:13:26] [CRIT] STMTURB12 decoupling sequence forced by thermal risk. Energy conversion is terminated.\\n[2026-04-25 17:19:08] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised.\\n[2026-04-25 17:20:27] [CRIT] STMTURB12 decoupling sequence forced by thermal risk. Energy conversion is terminated.\\n[2026-04-25 17:20:53] [CRIT] ECCS8 reported runaway outlet temperature. Protection interlock initiated reactor trip.\\n[2026-04-25 17:21:46] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 17:38:52] [CRIT] PWR01 can no longer sustain stable feed for cooling auxiliaries. Critical loads are shedding.\\n[2026-04-25 17:39:45] [CRIT] PWR01 can no longer sustain stable feed for cooling auxiliaries. Critical loads are shedding.\\n[2026-04-25 17:40:37] [CRIT] WSTPOOL2 absorption path reached emergency boundary. Heat rejection is no longer sufficient.\\n[2026-04-25 17:50:43] [CRIT] PWR01 can no longer sustain stable feed for cooling auxiliaries. Critical loads are shedding.\\n[2026-04-25 17:53:21] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 17:59:29] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 18:00:48] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 18:17:28] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised.\\n[2026-04-25 18:17:54] [CRIT] ECCS8 core cooling cannot maintain safe gradient. Immediate protective actions are required.\\n[2026-04-25 18:22:17] [CRIT] ECCS8 core cooling cannot maintain safe gradient. Immediate protective actions are required.\\n[2026-04-25 18:32:22] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised.\\n[2026-04-25 18:38:04] [CRIT] ECCS8 core cooling cannot maintain safe gradient. Immediate protective actions are required.\\n[2026-04-25 18:48:36] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised.\\n[2026-04-25 18:49:55] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 18:54:18] [CRIT] PWR01 can no longer sustain stable feed for cooling auxiliaries. Critical loads are shedding.\\n[2026-04-25 18:56:56] [CRIT] ECCS8 core cooling cannot maintain safe gradient. Immediate protective actions are required.\\n[2026-04-25 19:11:24] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 19:11:50] [CRIT] PWR01 can no longer sustain stable feed for cooling auxiliaries. Critical loads are shedding.\\n[2026-04-25 19:16:14] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 19:19:44] [CRIT] PWR01 can no longer sustain stable feed for cooling auxiliaries. Critical loads are shedding.\\n[2026-04-25 19:20:10] [CRIT] WTANK07 coolant level is below critical threshold. Shutdown logic is moving to hard trip stage.\\n[2026-04-25 19:24:34] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised.\\n[2026-04-25 19:34:39] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 19:41:40] [CRIT] ECCS8 reported runaway outlet temperature. Protection interlock initiated reactor trip.\\n[2026-04-25 19:50:00] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised.\\n[2026-04-25 19:50:52] [CRIT] ECCS8 core cooling cannot maintain safe gradient. Immediate protective actions are required.\\n[2026-04-25 19:54:49] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 19:56:34] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 19:57:27] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 19:58:46] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 19:59:39] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised.\\n[2026-04-25 20:04:54] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 20:05:21] [CRIT] Critical boundary exceeded on ECCS8. Emergency interlock keeps the reactor in protected mode.\\n[2026-04-25 20:06:40] [CRIT] PWR01 can no longer sustain stable feed for cooling auxiliaries. Critical loads are shedding.\\n[2026-04-25 20:07:06] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 20:07:32] [CRIT] WTANK07 coolant level is below critical threshold. Shutdown logic is moving to hard trip stage.\\n[2026-04-25 20:08:51] [CRIT] ECCS8 reported runaway outlet temperature. Protection interlock initiated reactor trip.\\n[2026-04-25 20:09:44] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 20:10:10] [CRIT] STMTURB12 decoupling sequence forced by thermal risk. Energy conversion is terminated.\\n[2026-04-25 20:10:36] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 20:11:55] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 20:12:22] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised.\\n[2026-04-25 20:13:14] [CRIT] ECCS8 reported runaway outlet temperature. Protection interlock initiated reactor trip.\\n[2026-04-25 20:15:26] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 20:19:23] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 20:22:27] [CRIT] ECCS8 core cooling cannot maintain safe gradient. Immediate protective actions are required.\\n[2026-04-25 20:23:46] [CRIT] PWR01 can no longer sustain stable feed for cooling auxiliaries. Critical loads are shedding.\\n[2026-04-25 20:24:12] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 20:28:09] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 20:29:54] [CRIT] PWR01 can no longer sustain stable feed for cooling auxiliaries. Critical loads are shedding.\\n[2026-04-25 20:32:06] [CRIT] Coolant inventory in WTANK07 is below critical threshold for full-loop operation. ECCS8 cannot guarantee reactor heat removal and automatic shutdown is mandatory.\\n[2026-04-25 20:33:25] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised.\\n[2026-04-25 20:33:51] [CRIT] PWR01 can no longer sustain stable feed for cooling auxiliaries. Critical loads are shedding.\\n[2026-04-25 20:36:03] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 20:37:21] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 20:38:14] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 20:39:33] [CRIT] PWR01 can no longer sustain stable feed for cooling auxiliaries. Critical loads are shedding.\\n[2026-04-25 20:41:18] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 20:42:37] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 20:43:04] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 20:47:27] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised.\\n[2026-04-25 20:48:19] [CRIT] WTANK07 coolant level is below critical threshold. Shutdown logic is moving to hard trip stage.\\n[2026-04-25 20:50:05] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 20:50:57] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 20:59:17] [CRIT] Insufficient cooling capacity confirmed after incomplete WTANK07 refill. Reactor protection system executes final shutdown sequence.\\n[2026-04-25 21:00:10] [CRIT] WTANK07 coolant level is below critical threshold. Shutdown logic is moving to hard trip stage.\\n[2026-04-25 21:00:36] [CRIT] WSTPOOL2 absorption path reached emergency boundary. Heat rejection is no longer sufficient.\\n[2026-04-25 21:03:14] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised.\\n[2026-04-25 21:04:33] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 21:05:25] [CRIT] STMTURB12 decoupling sequence forced by thermal risk. Energy conversion is terminated.\\n[2026-04-25 21:05:52] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 21:08:30] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 21:08:56] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked.\\n[2026-04-25 21:14:12] [CRIT] WSTPOOL2 absorption path reached emergency boundary. Heat rejection is no longer sufficient.\\n[2026-04-25 21:16:50] [CRIT] WSTPOOL2 absorption path reached emergency boundary. Heat rejection is no longer sufficient.\\n[2026-04-25 21:22:58] [CRIT] WTANK07 coolant level is below critical threshold. Shutdown logic is moving to hard trip stage.\\n[2026-04-25 21:24:43] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised.\\n[2026-04-25 21:26:28] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop.\\n[2026-04-25 21:27:47] [CRIT] WTANK07 coolant level is below critical threshold. Shutdown logic is moving to hard trip stage.\\n[2026-04-25 21:33:29] [CRIT] ECCS8 reported runaway outlet temperature. Protection interlock initiated reactor trip.\\n[2026-04-25 21:37:00] [CRIT] Final trip complete because WTANK07 remained under critical water level. FIRMWARE confirms safe shutdown state with all core operations halted."', 'tool_call_id': 'call_HmWLLTbiLTmON9CIulfbrGyI'}

--- Iteration 2 ---
Response message

In [93]:
print(w)

[
"[2026-04-25 06:04:13] [CRIT] ECCS8 reported runaway outlet temperature. Protection interlock initiated reactor trip. (x9 similar)",
"[2026-04-25 08:00:26] [CRIT] ECCS8 core cooling cannot maintain safe gradient. Immediate protective actions are required. (x9 similar)",
"[2026-04-25 19:54:49] [CRIT] ECCS8 cannot remove heat with the current WTANK07 volume. Reactor protection initiates critical stop. (x22 similar)",
"[2026-04-25 20:05:21] [CRIT] Critical boundary exceeded on ECCS8. Emergency interlock keeps the reactor in protected mode.",
"[2026-04-25 11:01:33] [CRIT] WTRPMP lost stable prime under peak thermal demand. Core loop continuity is compromised. (x15 similar)",
"[2026-04-25 13:37:40] [CRIT] PWR01 can no longer sustain stable feed for cooling auxiliaries. Critical loads are shedding. (x14 similar)",
"[2026-04-25 12:51:11] [CRIT] FIRMWARE entered emergency guard branch after repeated safety faults. Manual override is locked. (x16 similar)",
"[2026-04-25 12:56:27] [CRIT] STMTURB12 decoupling sequence forced by thermal risk. Energy conversion is terminated. (x6 similar)",
"[2026-04-25 06:16:56] [CRIT] WSTPOOL2 absorption path reached emergency boundary. Heat rejection is no longer sufficient. (x9 similar)",
"[2026-04-25 10:15:56] [CRIT] WTANK07 coolant level is below critical threshold. Shutdown logic is moving to hard trip stage. (x7 similar)",
"[2026-04-25 20:32:06] [CRIT] Coolant inventory in WTANK07 is below critical threshold for full-loop operation. ECCS8 cannot guarantee reactor heat removal and automatic shutdown is mandatory.",
"[2026-04-25 14:52:40] [CRIT] Safety bootstrap read missing environment marker SAFETY_CHECK=pass. FIRMWARE continues in restricted validation mode.",
"[2026-04-25 16:06:47] [CRIT] WSTPOOL2 entered critical protection state during startup. Immediate shutdown safeguards remain active.",
"[2026-04-25 20:59:17] [CRIT] Insufficient cooling capacity confirmed after incomplete WTANK07 refill. Reactor protection system executes final shutdown sequence.",
"[2026-04-25 21:37:00] [CRIT] Final trip complete because WTANK07 remained under critical water level. FIRMWARE confirms safe shutdown state with all core operations halted."
]

In [170]:
tekst = "FLAG"
odp = []
for i in range(1,130):
    time.sleep(0.2)
    odp_curr = submit_log(tekst)
    print(i,odp_curr)
    odp.append(odp_curr)
    if i%2==1:
        tekst = tekst + "\n"
    else:
        tekst = tekst + "FLAG"

1 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
2 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
3 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
4 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
5 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
6 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
7 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
8 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
9 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
10 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
11 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
12 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
13 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
14 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
15 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
16 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
17 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
18 {'status_code': 400, 'message': {'code': -960, 'message': 'These logs seem too short to analyze. Add more lines.'}}
19 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 19, 'lineCount': 10, 'noLetterSent': ''}}
20 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 19, 'lineCount': 10, 'noLetterSent': ''}}
21 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 21, 'lineCount': 11, 'noLetterSent': ''}}
22 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 21, 'lineCount': 11, 'noLetterSent': ''}}
23 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 23, 'lineCount': 12, 'noLetterSent': ''}}
24 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 23, 'lineCount': 12, 'noLetterSent': ''}}
25 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 25, 'lineCount': 13, 'noLetterSent': ''}}
26 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 25, 'lineCount': 13, 'noLetterSent': ''}}
27 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 27, 'lineCount': 14, 'noLetterSent': ''}}
28 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 27, 'lineCount': 14, 'noLetterSent': ''}}
29 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 29, 'lineCount': 15, 'noLetterSent': ''}}
30 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 29, 'lineCount': 15, 'noLetterSent': ''}}
31 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 31, 'lineCount': 16, 'noLetterSent': ''}}
32 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 31, 'lineCount': 16, 'noLetterSent': ''}}
33 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 33, 'lineCount': 17, 'noLetterSent': ''}}
34 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 33, 'lineCount': 17, 'noLetterSent': ''}}
35 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 35, 'lineCount': 18, 'noLetterSent': ''}}
36 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 35, 'lineCount': 18, 'noLetterSent': ''}}
37 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 37, 'lineCount': 19, 'noLetterSent': ''}}
38 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 37, 'lineCount': 19, 'noLetterSent': ''}}
39 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 39, 'lineCount': 20, 'noLetterSent': ''}}
40 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 39, 'lineCount': 20, 'noLetterSent': ''}}
41 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 41, 'lineCount': 21, 'noLetterSent': ''}}
42 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 41, 'lineCount': 21, 'noLetterSent': ''}}
43 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 43, 'lineCount': 22, 'noLetterSent': ''}}
44 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 43, 'lineCount': 22, 'noLetterSent': ''}}
45 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 45, 'lineCount': 23, 'noLetterSent': ''}}
46 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 45, 'lineCount': 23, 'noLetterSent': ''}}
47 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 47, 'lineCount': 24, 'noLetterSent': ''}}
48 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 47, 'lineCount': 24, 'noLetterSent': ''}}
49 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 49, 'lineCount': 25, 'noLetterSent': ''}}
50 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 49, 'lineCount': 25, 'noLetterSent': ''}}
51 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 51, 'lineCount': 26, 'noLetterSent': ''}}
52 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 51, 'lineCount': 26, 'noLetterSent': ''}}
53 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 53, 'lineCount': 27, 'noLetterSent': ''}}
54 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 53, 'lineCount': 27, 'noLetterSent': ''}}
55 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 55, 'lineCount': 28, 'noLetterSent': ''}}
56 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 55, 'lineCount': 28, 'noLetterSent': ''}}
57 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 57, 'lineCount': 29, 'noLetterSent': ''}}
58 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 57, 'lineCount': 29, 'noLetterSent': ''}}
59 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 59, 'lineCount': 30, 'noLetterSent': ''}}
60 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 59, 'lineCount': 30, 'noLetterSent': ''}}
61 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 61, 'lineCount': 31, 'noLetterSent': ''}}
62 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 61, 'lineCount': 31, 'noLetterSent': ''}}
63 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 63, 'lineCount': 32, 'noLetterSent': ''}}
64 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 63, 'lineCount': 32, 'noLetterSent': ''}}
65 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 65, 'lineCount': 33, 'letter': 'A'}}
66 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 65, 'lineCount': 33, 'letter': 'A'}}
67 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 67, 'lineCount': 34, 'letter': 'C'}}
68 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 67, 'lineCount': 34, 'letter': 'C'}}
69 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 69, 'lineCount': 35, 'letter': 'E'}}
70 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 69, 'lineCount': 35, 'letter': 'E'}}
71 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 71, 'lineCount': 36, 'letter': 'G'}}
72 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 71, 'lineCount': 36, 'letter': 'G'}}
73 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 73, 'lineCount': 37, 'letter': 'I'}}
74 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 73, 'lineCount': 37, 'letter': 'I'}}
75 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 75, 'lineCount': 38, 'letter': 'K'}}
76 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 75, 'lineCount': 38, 'letter': 'K'}}
77 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 77, 'lineCount': 39, 'letter': 'M'}}
78 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 77, 'lineCount': 39, 'letter': 'M'}}
79 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 79, 'lineCount': 40, 'letter': 'O'}}
80 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 79, 'lineCount': 40, 'letter': 'O'}}
81 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 81, 'lineCount': 41, 'letter': 'Q'}}
82 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 81, 'lineCount': 41, 'letter': 'Q'}}
83 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 83, 'lineCount': 42, 'letter': 'S'}}
84 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 83, 'lineCount': 42, 'letter': 'S'}}
85 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 85, 'lineCount': 43, 'letter': 'U'}}
86 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 85, 'lineCount': 43, 'letter': 'U'}}
87 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 87, 'lineCount': 44, 'letter': 'W'}}
88 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 87, 'lineCount': 44, 'letter': 'W'}}
89 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 89, 'lineCount': 45, 'letter': 'Y'}}
90 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 89, 'lineCount': 45, 'letter': 'Y'}}
91 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 91, 'lineCount': 46, 'letter': '['}}
92 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 91, 'lineCount': 46, 'letter': '['}}
93 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 93, 'lineCount': 47, 'letter': ']'}}
94 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 93, 'lineCount': 47, 'letter': ']'}}
95 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 95, 'lineCount': 48, 'letter': '_'}}
96 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 95, 'lineCount': 48, 'letter': '_'}}
97 {'status_code': 400, 'message': {'code': -949, 'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.', 'tokenCount': 97, 'lineCount': 49, 'letter': 'a'}}

In [195]:
def generate_string_tokens(num_tokens):
    words = []
    if num_tokens%2 == 1:
        n_lines = (num_tokens+1)//2
    else:
        n_lines = num_tokens//2
    for i in range(n_lines):
        word = 'FLAG'
        words.append(word)
    w = '\n'.join(words)
    if num_tokens%2 == 0:
        w = w+" F"
    return w

In [181]:
submit_log(""""FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
""")

{'status_code': 400,
 'message': {'code': -949,
  'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.',
  'tokenCount': 70,
  'lineCount': 35,
  'letter': 'F'}}

In [179]:
submit_log(""""
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG L
""")

{'status_code': 400,
 'message': {'code': -949,
  'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.',
  'tokenCount': 76,
  'lineCount': 38,
  'letter': 'L'}}

In [196]:
print(generate_string_tokens(29))

FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG

In [197]:
submit_log(generate_string_tokens(29))

{'status_code': 400,
 'message': {'code': -949,
  'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.',
  'tokenCount': 29,
  'lineCount': 15,
  'noLetterSent': ''}}

In [198]:
print(generate_string_tokens(30))

FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG
FLAG F

In [199]:
submit_log(generate_string_tokens(30))

{'status_code': 400,
 'message': {'code': -949,
  'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.',
  'tokenCount': 30,
  'lineCount': 15,
  'noLetterSent': ''}}

In [204]:
submit_log(generate_string_tokens(ord('F')))

{'status_code': 400,
 'message': {'code': -949,
  'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.',
  'tokenCount': 70,
  'lineCount': 35,
  'letter': 'F'}}

In [205]:
submit_log(generate_string_tokens(ord('L')))

{'status_code': 400,
 'message': {'code': -949,
  'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.',
  'tokenCount': 76,
  'lineCount': 38,
  'letter': 'L'}}

In [206]:
submit_log(generate_string_tokens(ord('A')))

{'status_code': 400,
 'message': {'code': -949,
  'message': 'Thanks for sending the logs. Unfortunately, our technicians still do not know what happened to STMTURB12.',
  'tokenCount': 65,
  'lineCount': 33,
  'letter': 'A'}}

In [207]:
submit_log(generate_string_tokens(ord('G')))

{'status_code': 200,
 'message': {'code': 100, 'message': 'Secret: {FLG:VIBECODER}'}}